### PR TITLE
configure only if the .in file is newer than the confifured file

### PR DESCRIPTION
**Pull request by romainhild**
Until now, after each cmake we need to recompile ipopt because we configure two files during the cmake.
We just need to check if the file is newer or not.

This was described in feelpp/feelpp#955 by @prudhomm

### CODE REVIEW

**Comment by gdolle** [comment]
Just a remark about this patch.
Be aware that if the cmake change (after a system lib update for example), you will need to remove the config.h to ensure autoconf is rerun.

**Comment by romainhild** [comment]
Yeah maybe we should add a warning or some message in the readme. 
If you do do `git submodule update --init --recursive` it will not touch the files ?

**Comment by gdolle** [comment]
Yes that may be a solution. At least we have a trace on this issue :)

**Comment by romainhild** [comment]
how do we update in feelpp the commit the submodule points to ?

**Comment by romainhild** [comment]
I think I just did it in the branch maxwell toolbox. There is other contrib with new commits (hppdm, mongocxx,jsonlab) @prudhomm should I also update them ?

**Comment by prudhomm** [comment]
the module has been moved forward in Feel++ see https://github.com/feelpp/feelpp/commit/b9b7cde3008f22e00a1745cad5bd253e301de39c

**Comment by romainhild** [comment]
Ah of course, I should have merge develop...

**Pull request merged**
